parametere = [
   'mean(surface_snow_thickness P1M)',
   'mean(surface_snow_thickness P3M)',
   'mean(surface_snow_thickness PT1H)',
   'min(surface_snow_thickness P1M)',
   'min(surface_snow_thickness P3M)',
   'max(surface_snow_thickness P1M)',
   'max(surface_snow_thickness P3M)',
   'cloud_area_fraction',
   'best_estimate_mean(air_temperature_anomaly P1M 1991_2020)',
   'air_temperature',
   'best_estimate_max(air_temperature P1D)',
   'best_estimate_mean(air_temperature P1D)',
   'best_estimate_mean(air_temperature P1M)',
   'best_estimate_mean(air_temperature P1Y)',
   'best_estimate_mean(air_temperature P3M)',
   'best_estimate_mean(air_temperature_anomaly P1Y 1991_2020)',
   'best_estimate_mean(air_temperature_anomaly P3M 1991_2020)',
   'best_estimate_min(air_temperature P1D)',
   'sum(precipitation_amount P1D)',
   'sum(precipitation_amount P1M)',
   'sum(precipitation_amount P1Y)',
   'sum(precipitation_amount P3M)',
   'sum(precipitation_amount P6M)',
   'sum(precipitation_amount P30D)',
   'sum(precipitation_amount PT1H)',
   'max(sum(precipitation_amount P1D) P1M)',
   'number_of_days_gte(sum(precipitation_amount P1D) P1M 1.0)',
   'number_of_days_gte(sum(precipitation_amount_normal P1D 1991_2020) P1Y 1.0)',
   'over_time(sum(time_of_maximum_precipitation_amount P1D) P1M)',
   'sum(precipitation_amount PT12H)',
   'sum(precipitation_amount_anomaly P1M 1971_2000)',
   'sum(precipitation_amount_anomaly P1M 1991_2020)',
   'sum(precipitation_amount_normal P1Y 1991_2020)',
   'max(wind_speed PT1H)',
   'max(wind_speed_of_gust PT1H)',
   'max_wind_speed(wind_from_direction PT1H)',
   'max_wind_speed(wind_from_direction_of_gust PT1H)',
   'wind_from_direction',
   'wind_from_direction_of_gust',
   'wind_speed',
   'wind_speed_of_gust'
]